server {
    listen 80;
    server_name inzaar.duckdns.org;

    location / {
        proxy_pass http://localhost:8000;
    }

    # Serve static uploaded files
    location /uploads/ {
        alias /root/INZAAR_DAASHBOARD_BEND/uploads/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
    }

    location /socket.io/ {
        proxy_pass http://localhost:8000;
    }
}
